/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
import { Level, MarginBottom, MarginLeft, MarginRight, MarginTop, PaddingBottom, PaddingLeft, PaddingRight, PaddingTop, } from "./components/units";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface MicroBox {
        "marginBottom": MarginBottom;
        "marginLeft": MarginLeft;
        "marginRight": MarginRight;
        "marginTop": MarginTop;
        "paddingBottom": PaddingBottom;
        "paddingLeft": PaddingLeft;
        "paddingRight": PaddingRight;
        "paddingTop": PaddingTop;
    }
    interface MicroButton {
    }
    interface MicroHeader {
        "level": Level;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLMicroBoxElement extends Components.MicroBox, HTMLStencilElement {
    }
    var HTMLMicroBoxElement: {
        prototype: HTMLMicroBoxElement;
        new (): HTMLMicroBoxElement;
    };
    interface HTMLMicroButtonElement extends Components.MicroButton, HTMLStencilElement {
    }
    var HTMLMicroButtonElement: {
        prototype: HTMLMicroButtonElement;
        new (): HTMLMicroButtonElement;
    };
    interface HTMLMicroHeaderElement extends Components.MicroHeader, HTMLStencilElement {
    }
    var HTMLMicroHeaderElement: {
        prototype: HTMLMicroHeaderElement;
        new (): HTMLMicroHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "micro-box": HTMLMicroBoxElement;
        "micro-button": HTMLMicroButtonElement;
        "micro-header": HTMLMicroHeaderElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface MicroBox {
        "marginBottom"?: MarginBottom;
        "marginLeft"?: MarginLeft;
        "marginRight"?: MarginRight;
        "marginTop"?: MarginTop;
        "paddingBottom"?: PaddingBottom;
        "paddingLeft"?: PaddingLeft;
        "paddingRight"?: PaddingRight;
        "paddingTop"?: PaddingTop;
    }
    interface MicroButton {
    }
    interface MicroHeader {
        "level"?: Level;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "micro-box": MicroBox;
        "micro-button": MicroButton;
        "micro-header": MicroHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "micro-box": LocalJSX.MicroBox & JSXBase.HTMLAttributes<HTMLMicroBoxElement>;
            "micro-button": LocalJSX.MicroButton & JSXBase.HTMLAttributes<HTMLMicroButtonElement>;
            "micro-header": LocalJSX.MicroHeader & JSXBase.HTMLAttributes<HTMLMicroHeaderElement>;
        }
    }
}
